---
- hosts: nodes
  gather_facts: yes
  become: true
  remote_user: ansible

  tasks:

  - name: Copy wikipedia data
    copy:
      src: ../templates/wikipedia.dat
      dest: /home/spark/wikipedia.dat

      
