---
- hosts: nodes
  gather_facts: yes
  become: true
  remote_user: ansible

  tasks:
  - name: Create conf dir for telegraf
    command: "mkdir -p /etc/telegraf/"

  - name: Copy telegraf and influxdb rpm repo to node1
    copy:
      src: ../templates/influxdb.repo
      dest: /etc/yum.repos.d/influxdb.repo

  - name: yum install telegraf
    yum:
      name: telegraf
      state: latest

  - name: Copy telegraf conf to node1
    copy:
      src: ../templates/telegraf-statsd.conf
      dest: /etc/telegraf/telegraf.conf
    when: ansible_nodename == "node1"

  - name: Copy telegraf conf to node0 and node2
    copy:
      src: ../templates/telegraf.conf
      dest: /etc/telegraf/telegraf.conf
    when: ansible_nodename != "node1"

  - name: start telegraf
    command: "systemctl restart telegraf"

  - name: enable telegraf
    command: "systemctl enable telegraf"
